### ISSUE TITLE
I'd suggest giving this set a more distinctive name.

### ISSUE THREAD

**Issue by claiire** [flugsio/chess_shapes#1]
I use your chess pieces on lichess all the time. I really loved them when I saw them but it took me a while to find out who designed them. If your set had a more distinctive, unique name it would be easier to find the creator, since "Shapes" is somewhat vague and difficult to search for. 

(I'm new to github so I apologize if people don't normally do this sort of things and I'm overstepping my bounds here.)

**Comment by Unihedro** [comment]
Would you like it to be named "flugsio" instead?

**Comment by claiire** [comment]
That seems better. Searching "Flugsio" brings up github.com/flugsio as the first page, so it's definitely more optimized for searching. Something like "Flugsio Set" or "Flugsio-Styled Pieces" would work very well.

**Comment by Unihedro** [comment]
I wasn't seriously suggesting that as a name, just that there is no _distinctive_ name that suits the set aside from the name of the creator. The set has three specific features:
- Original.
- For Lichess, as a chess set.
- Pieces are shapes.
- It's made by flugsio.

Aside from those, the set doesn't have much historical significance since it's pretty much "new". Point 1 doesn't do much good, mix point 2 and 3 and you get "chess_shapes". The key is therefore "shapes".

"flugsio" was a joke name, but on second thought, it might actually work as a name for the piece set. Also, like the other sets, it's expected that the key is one single word, so "Flugsio Set" or "Flugsio-Styled Pieces" both failed this criteria.

**Comment by Unihedro** [comment]
Also, it's not like there's another "shapes" chess set that I know of.

**Comment by claiire** [comment]
Issue closed I guess. You're right, I shouldn't have brought it up.

**Comment by flugsio** [comment]
Thanks for bringing this up and the discussion. Naming is hard and any suggestion is appreciated, but I'm probably not gonna rename it unless something really good comes up.

I still feel like finding out who made which set and finding the originals is somewhat hard, for lichess it can be tracked down from the commit where the svgs was added... but could maybe be improved with a complete list somewhere
